### ISSUE TITLE
Create communication to "netlink"

### ISSUE THREAD

**Issue by Sirherobrine23** [Sirherobrine23/Wireguard-tools.js#1]
We need to do a critical maintenance on the module, I don't want to be resorting to execute several commands reaching the PID of the host system, besides being considered much slower.

It will have to be implementing a netlink communication for Wireguard in the Linux kernel, and a userspace deployment for the others.

## TODO

- [x] Learning to use the module [netlink](https://github.com/mildsunrise/node_netlink).
  - [ ] get devices.
  - [ ] add new interface.
  - [ ] Delete interface
  - [ ] Add peer.
  - [ ] remove peer.
  - [ ] update peer (so remove the peer and add again).

**Comment by Sirherobrine23** [comment]
looks like i will have to check device by device, i will have filters like in this email: https://yhbt.net/lore/all/4de6eec9-9239-5e4e-60c1-e287b3be336a@gmail.com/t/

**Comment by Sirherobrine23** [comment]
I'm failing to get the peers with the [netlink](https://github.com/mildsunrise/node_netlink) module, if I don't succeed with the module I will have to create the add-on (I don't understand anything about C++)

**Comment by Sirherobrine23** [comment]
Request show:
'1400000003000200cbcbd062816f000000000000' (Is in hex buffer)

**Comment by Sirherobrine23** [comment]
Netlink parsed:

```json
{
  "show": {
    "x": {
      "type": "3",
      "flags": "2",
      "seq": "1657850942",
      "port": "30000",
      "data": "\u0000\u0000\u0000\u0000"
    },
    "consumed": "20"
  },
  "showAll": {
    "x": {
      "type": "3",
      "flags": "2",
      "seq": "1657851144",
      "port": "31784",
      "data": "\u0000\u0000\u0000\u0000"
    },
    "consumed": "20"
  },
  "syncStrip": {
    "x": {
      "type": "3",
      "flags": "2",
      "seq": "1657851217",
      "port": "32342",
      "data": "\u0000\u0000\u0000\u0000"
    },
    "consumed": "20"
  }
}
```
