### ISSUE TITLE
Node addon TODO

### ISSUE THREAD

**Issue by Sirherobrine23** [Sirherobrine23/Wireguard-tools.js#6]
Aqui está um pequeno resumo do que terei que fazer dentro do módulo: 

Estarei reescrevendo o `wireguard embeddable` para o `C++` e separando alguns arquivos como a parte do `Netlink` para uma `class`.

Parte do Wireguard será renomeado e uma limpeza dentro do código deles.

# Netlink

- [x] Adicionar os endereços de IP diretamente e ass rotas pelo módulo sem a necessidade de executar o comando `ip`.
- [x] Criar a interface de rede.
- [x] Deletar a interface de rede.
- [x] Atualizar a interface de rede como remover/adicionar um endereço de IP.

# Wireguard

- [x] Pegar os `peer` da interface do Wireguard.
- [x] Adicionar vários peers.
- [x] Poder adicionar um Endpoint ao peer.
- [x] Adicionar os IPs permitidos ao peer.
